# Generated by Django 4.2.9 on 2025-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ticket_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('student', 'Student')], default='regular', max_length=20),
        ),
    ]
