# Generated by Django 4.2.9 on 2025-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_invitation_guest_name_invitation_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='qr_code_text',
            field=models.TextField(unique=True),
        ),
    ]
