# Generated by Django 4.2.9 on 2025-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_invitation_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='qr_code_text',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
