# Generated by Django 4.2.9 on 2026-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_invitation_qr_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('lecture', 'Lecture'), ('panel', 'Panel'), ('roundtable', 'Roundtable'), ('networking', 'Networking'), ('webinar', 'Webinar'), ('training', 'Training'), ('discussion', 'Discussion'), ('exhibition', 'Exhibition'), ('conference', 'Conference')], default='seminar', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('speaker', 'Speaker'), ('sponsor', 'Sponsor'), ('media', 'Media'), ('team', 'Team'), ('online', 'Online')], default='standard', max_length=20),
        ),
    ]
