# Generated by Django 4.2.9 on 2026-01-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_type_invitation_invitation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_type',
        ),
    ]
