# Generated by Django 4.2.9 on 2026-01-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_time_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
