# Generated by Django 4.2.9 on 2026-01-14 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('visit_event', 'Visit Event'), ('visit_venue', 'Visit Venue'), ('review', 'Review'), ('vote', 'Vote'), ('booking', 'Booking')], max_length=20)),
                ('target_type', models.CharField(choices=[('event', 'Event'), ('venue', 'Venue')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('vote_value', models.SmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'target_type', 'target_id'], name='recommendat_user_id_8c2bc7_idx'), models.Index(fields=['target_type', 'target_id'], name='recommendat_target__86561e_idx')],
            },
        ),
    ]
