# Generated by Django 4.2.9 on 2026-01-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteraction',
            name='extra_info',
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('visit_event', 'Visit Event'), ('visit_venue', 'Visit Venue'), ('review', 'Review'), ('vote', 'Vote'), ('booking', 'Booking'), ('registration', 'Registration')], max_length=20),
        ),
    ]
