# Generated by Django 4.2.9 on 2026-01-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='last_time_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
