# Generated by Django 4.2.9 on 2026-01-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_last_time_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image_url',
            field=models.ImageField(upload_to='venue_images/'),
        ),
    ]
